// THIS IS A TEMPORARY CLASS BY LUKAS; REMOVE THIS WHEN DEBUG WINDOW IS ADDED
// AND USE THAT INSTEAD OF THIS SHIT; DOTHRAKI ON THE OPEN FIELD NED;

// #define _GOD_MODE
// #define _DISABLE_RENDERING_DEAD_ENEMIES
#define SKILL_USED 2