// THIS IS A TEMPORARY CLASS BY LUKAS; REMOVE THIS WHEN DEBUG WINDOW IS ADDED
// AND USE THAT INSTEAD OF THIS SHIT; DOTHRAKI ON THE OPEN FIELD NED;

#define _GOD_MODE
// #define _DISABLE_RENDERING_DEAD_ENEMIES
//0: Bullet time	1: Grappling hook	2: Shield charge
#define SKILL_USED 0